[tool.pytest.ini_options]
testpaths = [
  "tests/test_modeling",
  "src/modules/model_ensemble/tests",
  #"tests",
  #"src/modules/enterodoc/tests",
  #"tests/test_wf_site_scrape",
]
norecursedirs = [
  ".vscode",
  "config",
  "logs",
  "pretrained_models",
  "dist",
  "build",
  "runs",
  "workflows",

  "tests/test_asr",
  "tests/test_site_scrape",
]